import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Unified documentation sidebar with explicit directory structure
  // Excludes plc-one and contact which have their own sidebars
  docsSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '01-get-started'}],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: '02-tutorials'}],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '03-guides'}],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '04-reference'}],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '05-use-cases'}],
    },
    {
      type: 'category',
      label: 'Resources',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '06-resources'}],
    },
  ],
  // PLC-ONE hardware documentation (separate product)
  plcOneSidebar: [{type: 'autogenerated', dirName: 'plc-one'}],
  // Contact and legal pages
  contact: [{type: 'autogenerated', dirName: 'contact'}],
};

export default sidebars;
